### ISSUE TITLE
Does not extract .csv files

### ISSUE THREAD

**Issue by xenei** [nel1391/BcsExtractor#3]
I was trying your tool to extract .csv files from the .bcs files, but it did not extract anything even after I used the command - `$bcsextractor extract scenario.g2～ -o csv`, do note this game has scenario.g2 archive file instead .tac files because this is a different vn, however the script files are still .bcs 
I am attaching the following file and the original file if you need to check it. Also this is the game I was trying - https://vndb.org/v426
[scenario.g2.zip](https://github.com/nel1391/BcsExtractor/files/7868131/scenario.g2.zip)

**Comment by nel1391** [comment]
Ah, that's a Rune visual novel which is not currently supported. I should make it more clear but the .bcs documentation [here](https://github.com/nel1391/BcsExtractor/blob/main/FileFormat.md#differences-with-rune-visual-novels) outlines the reason. In short, even if the extension is the same, the file format is different for Rune novels.

If you are actually looking to translate that visual novel, I could look into adding support for it in this tool. It's not too difficult but might take some time since I'd only be able to do work on it on the weekends.

**Comment by xenei** [comment]
Oh sorry I didn't expect there to be a note about Rune vns, and no I was only curious to look into scenario lines and read a bit but thanks for the reply.

**Comment by nel1391** [comment]
Just an fyi, I did add script extraction for Rune vns, but unfortunately the folder replacement doesn't seem to work specifically for Musume Shimai, so the extracted scripts can't be easily put back in.

Someone would have to figure out another way to do it or put them back in the g2 archive.

**Comment by xenei** [comment]
Hello @nel1391, Thank you the update and thank you for your work! The new update seems to working pretty fine for Musume Shimai, and I know that you mentioned about how it can't be re-inserted in the game, But I didn't had any issues like that. 
All I did was keep the .csv files that had " Story Text " in them and replace the others with original .BCS files - 
![asd](https://user-images.githubusercontent.com/91423244/166665290-dc2181d2-b179-4c72-84b7-55dbe1ea1be7.PNG)
